apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: portal-server
spec:
  selector:
    matchLabels:
      app: portal-server
  replicas: 2 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: portal-server
    spec:
      containers:
      - name: portal-server
        image: registry.eu-de.bluemix.net/crefosystemtest/portal-1.0.0
        ports:
        - containerPort: 4200
          name: server
